---

- name: Copy public key to host
  copy: src=id_rsa.pub dest=/usr/share mode=0755

- name: Insert key into authorized keys file
  shell: chdir=/root/.ssh cat /usr/share/id_rsa.pub >> /root/.ssh/authorized_keys
  
- name: Install apt-get updates
  command: apt-get update
  
- name: Upgrade via apt-get
  command: apt-get -q -y upgrade

- name: Install additional packages
  apt: name={{item}} state=present
  with_items:
   - bridge-utils
   - lsof
   - lvm2
   - openssh-server
   - sudo
   - tcpdump
   - vim
   
- name: Create br-mgmt Linux bridge
  command: brctl addbr br-mgmt

- name: Add interface to br-mgmt bridge 
  command: brctl addif br-mgmt eth3

- name: Bring br-mgmt bridge up
  command: ifconfig br-mgmt up
  
- name: Create br-vxlan Linux bridge
  command: brctl addbr br-vxlan

- name: Add interface to br-vxlan bridge 
  command: brctl addif br-vxlan eth2

- name: Bring br-vxlan bridge up
  command: ifconfig br-vxlan up
  
- name: Create br-vlan Linux bridge
  command: brctl addbr br-vlan

- name: Bring br-vlan bridge up
  command: ifconfig br-vlan up